### ISSUE TITLE
No property named GuiControl

### ISSUE THREAD

**Issue by gcailly** [TheArkive/GuiCtlExt_ahk2#5]
Hi,
(Thank you for all your AHK libraries !)
Here is an error message with AutoHotKey 2.0 beta 7.
![image](https://user-images.githubusercontent.com/109429289/187950831-8a6cf104-f929-4321-acd5-12764d49175d.png)

**Comment by TheArkive** [comment]
Oh crud, I may not have tested that as thoroughly as I should have.  Thanks for the report.

EDIT:  Same thing happens on my machine.

EDIT2:   Glad ya like the ahk2 libs 👍

**Comment by TheArkive** [comment]
fixed
